### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by rainmanhhh** [ziping-li/convue#8]
```
> vite build

vite v2.1.1 building for production...
✓ 45 modules transformed.
error during build:
Error: Transform failed with 6 errors:
assets/index.ea083a72.js:171:12: error: Transforming destructuring to the configured target environment ("chrome61", "edge16", "es2019", "firefox60", "safari11") is not supported yet
assets/index.ea083a72.js:207:29: error: Transforming destructuring to the configured target environment ("chrome61", "edge16", "es2019", "firefox60", "safari11") is not supported yet
assets/index.ea083a72.js:228:20: error: Transforming destructuring to the configured target environment ("chrome61", "edge16", "es2019", "firefox60", "safari11") is not supported yet
assets/index.ea083a72.js:235:20: error: Transforming destructuring to the configured target environment ("chrome61", "edge16", "es2019", "firefox60", "safari11") is not supported yet
assets/index.ea083a72.js:265:22: error: Transforming destructuring to the configured target environment ("chrome61", "edge16", "es2019", "firefox60", "safari11") is not supported yet
...
    at failureErrorWithLog (E:\workspace\vite\convue\node_modules\.pnpm\esbuild@0.9.3\node_modules\esbuild\lib\main.js:1195:15)
    at E:\workspace\vite\convue\node_modules\.pnpm\esbuild@0.9.3\node_modules\esbuild\lib\main.js:1056:33
    at E:\workspace\vite\convue\node_modules\.pnpm\esbuild@0.9.3\node_modules\esbuild\lib\main.js:566:9
    at handleIncomingPacket (E:\workspace\vite\convue\node_modules\.pnpm\esbuild@0.9.3\node_modules\esbuild\lib\main.js:655:9)
    at Socket.readFromStdout (E:\workspace\vite\convue\node_modules\.pnpm\esbuild@0.9.3\node_modules\esbuild\lib\main.js:533:7)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)

```

**Comment by rainmanhhh** [comment]
降级esbuild到0.9.2后解决
